import type { ComponentType } from "react"
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Bell,
  Building2,
  Calendar,
  Camera,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileSearch,
  Filter,
  FileSignature,
  GripVertical,
  Grid2x2,
  Inbox,
  Info,
  LayoutDashboard,
  Link2,
  List,
  Mail,
  Menu,
  MessageCircle,
  Pencil,
  Phone,
  Reply,
  Search,
  CirclePause,
  CirclePlay,
  ChartNoAxesCombined,
  SearchCheck,
  Send,
  Settings,
  Share2,
  SlidersHorizontal,
  TriangleAlert,
  Upload,
  UserRound,
  Users,
  X,
} from "lucide-react"
import {
  FaFacebookF,
  FaInstagram,
  FaLinkedinIn,
  FaTiktok,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6"
import {
  MdAdd,
  MdAddAPhoto,
  MdAlternateEmail,
  MdAnalytics,
  MdApartment,
  MdArchitecture,
  MdArticle,
  MdAssessment,
  MdAutoAwesome,
  MdAutoStories,
  MdBadge,
  MdBarChart,
  MdBathtub,
  MdBed,
  MdBusiness,
  MdCall,
  MdCampaign,
  MdCheckCircle,
  MdChecklist,
  MdCloudUpload,
  MdCorporateFare,
  MdDelete,
  MdDescription,
  MdDraw,
  MdDrafts,
  MdEventBusy,
  MdFavorite,
  MdFavoriteBorder,
  MdFileDownload,
  MdFolderShared,
  MdFormatBold,
  MdFormatItalic,
  MdFormatListBulleted,
  MdFormatQuote,
  MdHandshake,
  MdHistoryEdu,
  MdHome,
  MdHomeWork,
  MdHouse,
  MdHub,
  MdLeaderboard,
  MdLibraryBooks,
  MdLocationOn,
  MdPayments,
  MdPersonAdd,
  MdPersonSearch,
  MdPictureAsPdf,
  MdPublic,
  MdRealEstateAgent,
  MdRocketLaunch,
  MdSms,
  MdSquareFoot,
  MdStar,
  MdStarBorder,
  MdStraighten,
  MdTableView,
  MdTextsms,
  MdToggleOff,
  MdTrendingDown,
  MdTrendingUp,
  MdWork,
} from "react-icons/md"

import { cn } from "@/lib/utils"

type IconComponent = ComponentType<{
  className?: string
  "aria-hidden"?: boolean
}>

const appIconMap: Record<string, IconComponent> = {
  add: MdAdd,
  add_a_photo: MdAddAPhoto,
  alternate_email: MdAlternateEmail,
  analytics: MdAnalytics,
  apartment: MdApartment,
  architecture: MdArchitecture,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  article: MdArticle,
  assessment: MdAssessment,
  attach_file: MdAdd,
  auto_awesome: MdAutoAwesome,
  auto_stories: MdAutoStories,
  badge: MdBadge,
  bar_chart: MdBarChart,
  bathtub: MdBathtub,
  bed: MdBed,
  business: MdBusiness,
  calendar_month: Calendar,
  calendar_today: Calendar,
  call: MdCall,
  campaign: MdCampaign,
  check_circle: MdCheckCircle,
  checklist: MdChecklist,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: MdCloudUpload,
  contract: MdHandshake,
  corporate_fare: MdCorporateFare,
  dashboard: LayoutDashboard,
  database: Database,
  delete: MdDelete,
  description: MdDescription,
  document_scanner: FileSearch,
  domain: Building2,
  done: CheckCheck,
  done_all: CheckCheck,
  download: Download,
  drag_indicator: GripVertical,
  draw: MdDraw,
  edit: Pencil,
  event_busy: MdEventBusy,
  expand_more: ChevronDown,
  favorite: MdFavorite,
  favorite_border: MdFavoriteBorder,
  facebook: FaFacebookF,
  file_download: MdFileDownload,
  filter_list: Filter,
  folder_shared: MdFolderShared,
  format_bold: MdFormatBold,
  format_italic: MdFormatItalic,
  format_list_bulleted: MdFormatListBulleted,
  format_quote: MdFormatQuote,
  forum: MessageCircle,
  grid_view: Grid2x2,
  group: Users,
  handshake: MdHandshake,
  help_outline: CircleHelp,
  history_edu: MdHistoryEdu,
  timeline: ChartNoAxesCombined,
  home: MdHome,
  home_work: MdHomeWork,
  hourglass_empty: Clock3,
  house: MdHouse,
  hub: MdHub,
  inbox: Inbox,
  info: Info,
  instagram: FaInstagram,
  leaderboard: MdLeaderboard,
  library_books: MdLibraryBooks,
  linkedin: FaLinkedinIn,
  link: Link2,
  location_on: MdLocationOn,
  mail: Mail,
  mark_email_unread: Mail,
  menu: Menu,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: MdPayments,
  pause_circle: CirclePause,
  play_circle: CirclePlay,
  person: UserRound,
  person_add: MdPersonAdd,
  person_search: MdPersonSearch,
  phone: Phone,
  photo_camera: Camera,
  picture_as_pdf: MdPictureAsPdf,
  public: MdPublic,
  rate_review: MessageCircle,
  real_estate_agent: MdRealEstateAgent,
  reply: Reply,
  rocket_launch: MdRocketLaunch,
  search: Search,
  search_check: SearchCheck,
  send: Send,
  settings: Settings,
  share: Share2,
  signature: FileSignature,
  sms: MdSms,
  social_leaderboard: MdLeaderboard,
  square_foot: MdSquareFoot,
  star: MdStar,
  star_border: MdStarBorder,
  straighten: MdStraighten,
  sync: SlidersHorizontal,
  table_view: MdTableView,
  textsms: MdTextsms,
  toggle_off: MdToggleOff,
  trending_down: MdTrendingDown,
  trending_up: MdTrendingUp,
  tune: SlidersHorizontal,
  upload_file: Upload,
  verified: BadgeCheck,
  view_list: List,
  visibility: Eye,
  warning: TriangleAlert,
  work: MdWork,
  x_social: FaXTwitter,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  drafts: MdDrafts,
}

export function AppIcon({
  className,
  name,
}: {
  className?: string
  name?: string | null
}) {
  const Icon = (name ? appIconMap[name] : null) ?? Building2

  return (
    <Icon
      aria-hidden
      className={cn("inline-block h-[1em] w-[1em] shrink-0 align-middle", className)}
    />
  )
}
