using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    public partial class BackfillOwnerReportDispatchSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS property_owner_report_dispatch (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    property_id integer NOT NULL,
                    period_start timestamp with time zone NOT NULL DEFAULT now(),
                    period_end timestamp with time zone NOT NULL DEFAULT now(),
                    channels jsonb NOT NULL DEFAULT '[]',
                    subject text NOT NULL DEFAULT '',
                    body text NOT NULL DEFAULT '',
                    status integer NOT NULL DEFAULT 0,
                    summary text NOT NULL DEFAULT '',
                    created_by text NOT NULL DEFAULT '',
                    sent_at timestamp with time zone NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now()
                );

                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS subject text NOT NULL DEFAULT '';
                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS body text NOT NULL DEFAULT '';
                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS summary text NOT NULL DEFAULT '';
                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS created_by text NOT NULL DEFAULT '';
                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone NULL;
                ALTER TABLE property_owner_report_dispatch ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();
                CREATE INDEX IF NOT EXISTS ix_property_owner_report_dispatch_property_id ON property_owner_report_dispatch(property_id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
