using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    public partial class AddPropertyOperationsPublicAccess : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS property_operations_settings (
                    id integer PRIMARY KEY,
                    business_name varchar(200) NOT NULL DEFAULT 'Property Operations',
                    logo_url text NOT NULL DEFAULT '',
                    brand_color varchar(20) NOT NULL DEFAULT '#111827',
                    public_base_url text NOT NULL DEFAULT '',
                    default_expiry_hours integer NOT NULL DEFAULT 168,
                    default_max_uses integer NOT NULL DEFAULT 1,
                    default_one_time boolean NOT NULL DEFAULT true,
                    require_name boolean NOT NULL DEFAULT true,
                    require_email boolean NOT NULL DEFAULT false,
                    require_phone boolean NOT NULL DEFAULT false,
                    allow_file_uploads boolean NOT NULL DEFAULT true,
                    show_property_address boolean NOT NULL DEFAULT true,
                    auto_close_record_on_submit boolean NOT NULL DEFAULT false,
                    notify_admin_on_submit boolean NOT NULL DEFAULT true,
                    welcome_message text NOT NULL DEFAULT '',
                    terms_text text NOT NULL DEFAULT '',
                    email_subject_template text NOT NULL DEFAULT '',
                    email_body_template text NOT NULL DEFAULT '',
                    sms_template text NOT NULL DEFAULT '',
                    updated_at timestamp with time zone NOT NULL DEFAULT now()
                );

                INSERT INTO property_operations_settings (id)
                VALUES (1)
                ON CONFLICT (id) DO NOTHING;

                CREATE TABLE IF NOT EXISTS property_operations_public_access (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workspace_id integer NOT NULL,
                    record_id integer,
                    module_key varchar(80) NOT NULL,
                    title varchar(240) NOT NULL,
                    instructions text NOT NULL DEFAULT '',
                    recipient_label varchar(120) NOT NULL DEFAULT 'External recipient',
                    recipient_name varchar(160) NOT NULL DEFAULT '',
                    recipient_email varchar(240) NOT NULL DEFAULT '',
                    recipient_phone varchar(80) NOT NULL DEFAULT '',
                    token_hash varchar(64) NOT NULL,
                    status varchar(40) NOT NULL DEFAULT 'Active',
                    form_schema_json jsonb NOT NULL DEFAULT '[]'::jsonb,
                    expires_at timestamp with time zone NOT NULL,
                    max_uses integer NOT NULL DEFAULT 1,
                    use_count integer NOT NULL DEFAULT 0,
                    one_time boolean NOT NULL DEFAULT true,
                    allow_file_uploads boolean NOT NULL DEFAULT true,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    last_accessed_at timestamp with time zone,
                    completed_at timestamp with time zone,
                    revoked_at timestamp with time zone,
                    CONSTRAINT fk_property_operations_public_access_workspace
                        FOREIGN KEY (workspace_id) REFERENCES property_operations_workspace(id) ON DELETE CASCADE,
                    CONSTRAINT fk_property_operations_public_access_record
                        FOREIGN KEY (record_id) REFERENCES property_operations_record(id) ON DELETE SET NULL,
                    CONSTRAINT uq_property_operations_public_access_token UNIQUE (token_hash)
                );

                CREATE TABLE IF NOT EXISTS property_operations_public_submission (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    public_access_id integer NOT NULL,
                    responder_name varchar(160) NOT NULL DEFAULT '',
                    responder_email varchar(240) NOT NULL DEFAULT '',
                    responder_phone varchar(80) NOT NULL DEFAULT '',
                    notes text NOT NULL DEFAULT '',
                    response_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                    attachment_urls_json jsonb NOT NULL DEFAULT '[]'::jsonb,
                    submitted_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_property_operations_public_submission_access
                        FOREIGN KEY (public_access_id) REFERENCES property_operations_public_access(id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS property_operations_activity (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workspace_id integer,
                    module_key varchar(80) NOT NULL DEFAULT '',
                    action varchar(100) NOT NULL DEFAULT '',
                    entity_type varchar(80) NOT NULL DEFAULT '',
                    entity_id integer,
                    actor_type varchar(40) NOT NULL DEFAULT 'Admin',
                    summary text NOT NULL DEFAULT '',
                    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_property_operations_activity_workspace
                        FOREIGN KEY (workspace_id) REFERENCES property_operations_workspace(id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ix_property_operations_public_access_workspace_module
                    ON property_operations_public_access(workspace_id, module_key);
                CREATE INDEX IF NOT EXISTS ix_property_operations_public_access_status
                    ON property_operations_public_access(status);
                CREATE INDEX IF NOT EXISTS ix_property_operations_public_access_expires_at
                    ON property_operations_public_access(expires_at);
                CREATE INDEX IF NOT EXISTS ix_property_operations_public_submission_access_time
                    ON property_operations_public_submission(public_access_id, submitted_at);
                CREATE INDEX IF NOT EXISTS ix_property_operations_activity_workspace_time
                    ON property_operations_activity(workspace_id, created_at);
                CREATE INDEX IF NOT EXISTS ix_property_operations_activity_entity
                    ON property_operations_activity(entity_type, entity_id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS property_operations_activity;
                DROP TABLE IF EXISTS property_operations_public_submission;
                DROP TABLE IF EXISTS property_operations_public_access;
                DROP TABLE IF EXISTS property_operations_settings;
                """);
        }
    }
}
