// <auto-generated />
using System;
using System.Collections.Generic;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509182552_AddAgentId")]
    partial class AddAgentId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.AgencyIntegrationSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AiProviderPayload")
                        .HasColumnType("text")
                        .HasColumnName("ai_provider_payload");

                    b.Property<DateTime?>("AiProviderUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_provider_updated_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SmtpPayload")
                        .HasColumnType("text")
                        .HasColumnName("smtp_payload");

                    b.Property<DateTime?>("SmtpUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("smtp_updated_at");

                    b.Property<string>("TwilioPayload")
                        .HasColumnType("text")
                        .HasColumnName("twilio_payload");

                    b.Property<DateTime?>("TwilioUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("twilio_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agency_integration_settings");

                    b.ToTable("agency_integration_settings", (string)null);
                });

            modelBuilder.Entity("Entities.AgencySettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agency_settings");

                    b.ToTable("agency_settings", (string)null);
                });

            modelBuilder.Entity("Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CoverImageObjectName")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_object_name");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.PrimitiveCollection<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("highlights");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.PrimitiveCollection<string>("Paragraphs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("paragraphs");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ReadTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("read_time_minutes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blog_post");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_slug");

                    b.ToTable("blog_post", (string)null);
                });

            modelBuilder.Entity("Entities.BrokerageApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OldPrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_price");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("integer")
                        .HasColumnName("old_status");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("RequestNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_note");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<string>("RequestedPrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_price");

                    b.Property<int?>("RequestedStatus")
                        .HasColumnType("integer")
                        .HasColumnName("requested_status");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_brokerage_approval_request");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_brokerage_approval_request_property_id");

                    b.ToTable("brokerage_approval_request", (string)null);
                });

            modelBuilder.Entity("Entities.BrokerageAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_brokerage_audit_log");

                    b.ToTable("brokerage_audit_log", (string)null);
                });

            modelBuilder.Entity("Entities.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InquiryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inquiry_type");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contact_request");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_contact_request_lead_id");

                    b.ToTable("contact_request", (string)null);
                });

            modelBuilder.Entity("Entities.DealChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DealPipelineId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_pipeline_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deal_checklist_item");

                    b.HasIndex("DealPipelineId")
                        .HasDatabaseName("ix_deal_checklist_item_deal_pipeline_id");

                    b.ToTable("deal_checklist_item", (string)null);
                });

            modelBuilder.Entity("Entities.DealPipeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_amount");

                    b.Property<string>("CommissionPayoutNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commission_payout_note");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<int>("CommissionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("commission_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deadline");

                    b.Property<DateTime?>("ExpectedClosingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_closing_date");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("SourceLeadId")
                        .HasColumnType("integer")
                        .HasColumnName("source_lead_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_deal_pipeline");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_deal_pipeline_agent_id");

                    b.HasIndex("SourceLeadId")
                        .HasDatabaseName("ix_deal_pipeline_source_lead_id");

                    b.ToTable("deal_pipeline", (string)null);
                });

            modelBuilder.Entity("Entities.DocumentRepositoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileObjectName")
                        .HasColumnType("text")
                        .HasColumnName("file_object_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<bool>("RequiresSignature")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_signature");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_label");

                    b.HasKey("Id")
                        .HasName("pk_document_repository_item");

                    b.ToTable("document_repository_item", (string)null);
                });

            modelBuilder.Entity("Entities.HomePageSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_home_page_settings");

                    b.ToTable("home_page_settings", (string)null);
                });

            modelBuilder.Entity("Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("FollowUpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("follow_up_status");

                    b.Property<bool>("InBoard")
                        .HasColumnType("boolean")
                        .HasColumnName("in_board");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interest");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_date");

                    b.Property<string>("NextActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("next_action_type");

                    b.PrimitiveCollection<string>("Notes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Timeline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeline");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lead");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_lead_agent_id");

                    b.ToTable("lead", (string)null);
                });

            modelBuilder.Entity("Entities.LeadAssignmentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("integer")
                        .HasColumnName("priority_order");

                    b.Property<int?>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lead_assignment_rule");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_lead_assignment_rule_agent_id");

                    b.ToTable("lead_assignment_rule", (string)null);
                });

            modelBuilder.Entity("Entities.LeadHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lead_history");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_history_lead_id");

                    b.ToTable("lead_history", (string)null);
                });

            modelBuilder.Entity("Entities.MailInboxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mail_inbox");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_mail_inbox_lead_id");

                    b.ToTable("mail_inbox", (string)null);
                });

            modelBuilder.Entity("Entities.MarketingSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_marketing_settings");

                    b.ToTable("marketing_settings", (string)null);
                });

            modelBuilder.Entity("Entities.NeighborhoodInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_neighborhood_insight");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_neighborhood_insight_property_id");

                    b.ToTable("neighborhood_insight", (string)null);
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("BathRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bath_room");

                    b.Property<string>("BedRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bed_room");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("DocumentRepositoryItemIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_repository_item_ids");

                    b.Property<string>("ExactLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exact_location");

                    b.PrimitiveCollection<string>("ImageObjectNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_object_names");

                    b.PrimitiveCollection<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_urls");

                    b.PrimitiveCollection<string>("KeyAmenities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_amenities");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailObjectName")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_object_name");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_property");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_property_agent_id");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("Entities.PropertyChatConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_agent");

                    b.Property<bool>("AutoQualified")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_qualified");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("budget");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interest");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_title");

                    b.Property<float>("QualificationScore")
                        .HasColumnType("real")
                        .HasColumnName("qualification_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Timeline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeline");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_property_chat_conversation");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_property_chat_conversation_lead_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_chat_conversation_property_id");

                    b.ToTable("property_chat_conversation", (string)null);
                });

            modelBuilder.Entity("Entities.PropertyChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentObjectName")
                        .HasColumnType("text")
                        .HasColumnName("attachment_object_name");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("SenderRole")
                        .HasColumnType("integer")
                        .HasColumnName("sender_role");

                    b.HasKey("Id")
                        .HasName("pk_property_chat_message");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_property_chat_message_conversation_id");

                    b.ToTable("property_chat_message", (string)null);
                });

            modelBuilder.Entity("Entities.PropertyPreQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsFileUpload")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_file_upload");

                    b.Property<string>("AttachmentObjectName")
                        .HasColumnType("text")
                        .HasColumnName("attachment_object_name");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HelperText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("helper_text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_property_pre_question");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_pre_question_property_id");

                    b.ToTable("property_pre_question", (string)null);
                });

            modelBuilder.Entity("Entities.ShowingBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_showing_booking");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_showing_booking_agent_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_showing_booking_lead_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_showing_booking_property_id");

                    b.ToTable("showing_booking", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AgencyName")
                        .HasColumnType("text")
                        .HasColumnName("agency_name");

                    b.PrimitiveCollection<List<string>>("AgentRoutePermissions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("agent_route_permissions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("first_name");

                    b.Property<bool>("HasCustomAgentRoutePermissions")
                        .HasColumnType("boolean")
                        .HasColumnName("has_custom_agent_route_permissions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone_verified");

                    b.Property<bool>("IsVerifiedAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified_agent");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expiry");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Entities.BrokerageApprovalRequest", b =>
                {
                    b.HasOne("Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brokerage_approval_request_property_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.ContactRequest", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany("ContactRequests")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contact_request_lead_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Entities.DealChecklistItem", b =>
                {
                    b.HasOne("Entities.DealPipeline", "DealPipeline")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("DealPipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_checklist_item_deal_pipeline_deal_pipeline_id");

                    b.Navigation("DealPipeline");
                });

            modelBuilder.Entity("Entities.DealPipeline", b =>
                {
                    b.HasOne("User", "DealOwner")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deal_pipeline_users_agent_id");

                    b.HasOne("Entities.Lead", "SourceLead")
                        .WithMany("Deals")
                        .HasForeignKey("SourceLeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deal_pipeline_lead_source_lead_id");

                    b.Navigation("DealOwner");

                    b.Navigation("SourceLead");
                });

            modelBuilder.Entity("Entities.Lead", b =>
                {
                    b.HasOne("User", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lead_users_agent_id");

                    b.Navigation("AssignedAgent");
                });

            modelBuilder.Entity("Entities.LeadAssignmentRule", b =>
                {
                    b.HasOne("User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_assignment_rule_users_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Entities.LeadHistoryEntry", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_history_lead_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Entities.MailInboxItem", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany("MailInboxItems")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mail_inbox_lead_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Entities.NeighborhoodInsight", b =>
                {
                    b.HasOne("Entities.Property", "Property")
                        .WithMany("NeighborhoodInsights")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_neighborhood_insight_property_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.HasOne("User", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_property_users_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Entities.PropertyChatConversation", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_property_chat_conversation_lead_lead_id");

                    b.HasOne("Entities.Property", "Property")
                        .WithMany("ChatConversations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_chat_conversation_property_property_id");

                    b.Navigation("Lead");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.PropertyChatMessage", b =>
                {
                    b.HasOne("Entities.PropertyChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_chat_message_property_chat_conversation_conversati");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Entities.PropertyPreQuestion", b =>
                {
                    b.HasOne("Entities.Property", "Property")
                        .WithMany("PreQuestions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_pre_question_property_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.ShowingBooking", b =>
                {
                    b.HasOne("User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_showing_booking_users_agent_id");

                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_showing_booking_lead_lead_id");

                    b.HasOne("Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_showing_booking_property_property_id");

                    b.Navigation("Agent");

                    b.Navigation("Lead");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.DealPipeline", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("Entities.Lead", b =>
                {
                    b.Navigation("ContactRequests");

                    b.Navigation("Deals");

                    b.Navigation("MailInboxItems");
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.Navigation("ChatConversations");

                    b.Navigation("NeighborhoodInsights");

                    b.Navigation("PreQuestions");
                });

            modelBuilder.Entity("Entities.PropertyChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
