using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    public partial class AddPropertyOperationsWorkspace : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS property_operations_workspace (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    property_id integer NOT NULL,
                    status varchar(40) NOT NULL DEFAULT 'Active',
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_property_operations_workspace_property
                        FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE,
                    CONSTRAINT uq_property_operations_workspace_property UNIQUE (property_id)
                );

                CREATE TABLE IF NOT EXISTS property_operations_module_state (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workspace_id integer NOT NULL,
                    module_key varchar(80) NOT NULL,
                    status varchar(40) NOT NULL DEFAULT 'Not started',
                    notes text NOT NULL DEFAULT '',
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_property_operations_module_state_workspace
                        FOREIGN KEY (workspace_id) REFERENCES property_operations_workspace(id) ON DELETE CASCADE,
                    CONSTRAINT uq_property_operations_module_state_workspace_module
                        UNIQUE (workspace_id, module_key)
                );

                CREATE TABLE IF NOT EXISTS property_operations_record (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workspace_id integer NOT NULL,
                    module_key varchar(80) NOT NULL,
                    record_type varchar(80) NOT NULL DEFAULT 'Item',
                    title varchar(240) NOT NULL,
                    description text NOT NULL DEFAULT '',
                    status varchar(60) NOT NULL DEFAULT 'Open',
                    priority varchar(40) NOT NULL DEFAULT 'Normal',
                    contact_name varchar(160) NOT NULL DEFAULT '',
                    contact_email varchar(240) NOT NULL DEFAULT '',
                    contact_phone varchar(80) NOT NULL DEFAULT '',
                    amount numeric(18,2),
                    due_at timestamp with time zone,
                    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    updated_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_property_operations_record_workspace
                        FOREIGN KEY (workspace_id) REFERENCES property_operations_workspace(id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ix_property_operations_module_state_workspace
                    ON property_operations_module_state(workspace_id);
                CREATE INDEX IF NOT EXISTS ix_property_operations_record_workspace_module
                    ON property_operations_record(workspace_id, module_key);
                CREATE INDEX IF NOT EXISTS ix_property_operations_record_status
                    ON property_operations_record(status);
                CREATE INDEX IF NOT EXISTS ix_property_operations_record_due_at
                    ON property_operations_record(due_at);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS property_operations_record;
                DROP TABLE IF EXISTS property_operations_module_state;
                DROP TABLE IF EXISTS property_operations_workspace;
                """);
        }
    }
}
