// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InquiryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inquiry_type");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contact_request");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_contact_request_lead_id");

                    b.ToTable("contact_request", (string)null);
                });

            modelBuilder.Entity("Entities.DealPipeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deadline");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("SourceLeadId")
                        .HasColumnType("integer")
                        .HasColumnName("source_lead_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_deal_pipeline");

                    b.HasIndex("SourceLeadId")
                        .HasDatabaseName("ix_deal_pipeline_source_lead_id");

                    b.ToTable("deal_pipeline", (string)null);
                });

            modelBuilder.Entity("Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("InBoard")
                        .HasColumnType("boolean")
                        .HasColumnName("in_board");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interest");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string>("Notes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Timeline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeline");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lead");

                    b.ToTable("lead", (string)null);
                });

            modelBuilder.Entity("Entities.MailInboxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mail_inbox");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_mail_inbox_lead_id");

                    b.ToTable("mail_inbox", (string)null);
                });

            modelBuilder.Entity("Entities.NeighborhoodInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_neighborhood_insight");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_neighborhood_insight_property_id");

                    b.ToTable("neighborhood_insight", (string)null);
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<string>("BathRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bath_room");

                    b.Property<string>("BedRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bed_room");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExactLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exact_location");

                    b.PrimitiveCollection<string>("ImageObjectNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_object_names");

                    b.PrimitiveCollection<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_urls");

                    b.PrimitiveCollection<string>("KeyAmenities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_amenities");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailObjectName")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_object_name");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_property");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_property_agent_id");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AgencyName")
                        .HasColumnType("text")
                        .HasColumnName("agency_name");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone_verified");

                    b.Property<bool>("IsVerifiedAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified_agent");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expiry");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Entities.ContactRequest", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany("ContactRequests")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contact_request_lead_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Entities.DealPipeline", b =>
                {
                    b.HasOne("Entities.Lead", "SourceLead")
                        .WithMany("Deals")
                        .HasForeignKey("SourceLeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deal_pipeline_lead_source_lead_id");

                    b.Navigation("SourceLead");
                });

            modelBuilder.Entity("Entities.MailInboxItem", b =>
                {
                    b.HasOne("Entities.Lead", "Lead")
                        .WithMany("MailInboxItems")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mail_inbox_lead_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Entities.NeighborhoodInsight", b =>
                {
                    b.HasOne("Entities.Property", "Property")
                        .WithMany("NeighborhoodInsights")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_neighborhood_insight_property_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.HasOne("User", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_property_users_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Entities.Lead", b =>
                {
                    b.Navigation("ContactRequests");

                    b.Navigation("Deals");

                    b.Navigation("MailInboxItems");
                });

            modelBuilder.Entity("Entities.Property", b =>
                {
                    b.Navigation("NeighborhoodInsights");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
