import { Globe2, Save } from "lucide-react"

import { requireDashboardAccess } from "@/lib/dashboard-auth"
import { getTenantProfile, updateAssignedSubdomainAction, updateTenantProfileAction } from "@/lib/tenant-dashboard-actions"

export default async function TenantSettingsPage() {
  await requireDashboardAccess("dashboard")
  const profile = await getTenantProfile()
  return <main className="mx-auto max-w-5xl space-y-8 p-5 sm:p-8 lg:p-10"><header><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#4343d5]">Tenant settings</p><h1 className="mt-2 text-3xl font-bold">Business profile</h1><p className="mt-2 text-sm text-slate-600">Manage the identity and public information stored in your tenant database.</p></header>
  <form action={updateTenantProfileAction} className="grid gap-5 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-semibold">Business name</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.businessName} name="businessName" required/></label><label className="space-y-2"><span className="text-sm font-semibold">Tagline</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.branding.tagline ?? ""} name="tagline"/></label><label className="space-y-2"><span className="text-sm font-semibold">Phone</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.homepage.phone ?? ""} name="phone"/></label><label className="space-y-2"><span className="text-sm font-semibold">Email</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.homepage.email ?? ""} name="email" type="email"/></label><label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">Address</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.homepage.address ?? ""} name="address"/></label><label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">Homepage headline</span><input className="h-12 w-full rounded-xl border px-4" defaultValue={profile.homepage.headline ?? ""} name="headline"/></label><label className="space-y-2 md:col-span-2"><span className="text-sm font-semibold">Homepage description</span><textarea className="min-h-32 w-full rounded-xl border p-4" defaultValue={profile.homepage.description ?? ""} name="description"/></label><button className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#4343d5] px-5 font-semibold text-white md:col-span-2"><Save className="size-4"/>Save business profile</button></form>
  <form action={updateAssignedSubdomainAction} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><Globe2 className="mt-1 size-5 text-[#4343d5]"/><div><h2 className="text-xl font-bold">Assigned subdomain</h2><p className="mt-1 text-sm text-slate-600">Change the tenant subdomain when the name is valid, unique, and not reserved.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input className="h-12 min-w-0 flex-1 rounded-xl border px-4" defaultValue={profile.subdomain} name="subdomain" pattern="[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?" required/><button className="h-12 rounded-xl bg-[#0b1c30] px-5 font-semibold text-white">Update subdomain</button></div></form></main>
}
